version: '3.8'

services:
  test-app-gunico:
    build:
      context: .
      dockerfile: Dockerfile.fla
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    # - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - FLASK_DEBUG=development
  test-req:
    build:
      context: .
      dockerfile: Dockerfile.req
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=development
