version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    # - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - FLASK_ENV=development

#  app-prod:
#    build:
#      context: .
#      dockerfile: Dockerfile.prod
#    ports:
#      - "8000:8000"
#    environment:
#      - FLASK_ENV=production