name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - archspec=0.2.1
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - conda=23.11.0
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=23.12.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.7
  - distro=1.8.0
  - fmt=10.1.1
  - idna=3.4
  - jsonpatch=1.32
  - jsonpointer=2.1
  - krb5=1.21.2
  - libarchive=3.7.2
  - libcurl=8.5.0
  - libffi=3.4.4
  - libiconv=1.17
  - libmamba=1.5.6
  - libmambapy=1.5.6
  - libsolv=0.7.24
  - libssh2=1.11.0
  - libxml2=2.12.3
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.6
  - menuinst=2.0.1
  - openssl=3.2.0
  - packaging=23.1
  - pcre2=10.42
  - pip=23.3.1
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.5
  - python_abi=3.11
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - ruamel.yaml=0.17.21
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tqdm=4.65.0
  - truststore=0.8.0
  - tzdata=2023c
  - urllib3=1.26.18
  - wheel=0.41.2
  - xz=5.4.5
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - bidict==0.22.0
      - blinker==1.7.0
      - cachelib==0.9.0
      - click==8.1.3
      - dnspython==2.5.0
      - eventlet==0.35.0
      - flask==2.2.5
      - flask-login==0.6.2
      - flask-session==0.4.0
      - flask-socketio==5.3.6
      - gevent==23.9.1
      - gevent-websocket==0.10.1
      - greenlet==3.0.3
      - gunicorn==21.2.0
      - h11==0.14.0
      - importlib-metadata==4.12.0
      - itsdangerous==2.1.2
      - jinja2==3.1.3
      - markupsafe==2.1.1
      - python-engineio==4.8.2
      - python-socketio==5.11.0
      - simple-websocket==1.0.0
      - six==1.11.0
      - werkzeug==2.2.3
      - wsproto==1.2.0
      - zipp==3.8.1
      - zope-event==5.0
      - zope-interface==6.1
